# Generated by Django 4.1.13 on 2024-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='names',
        ),
    ]
