# Generated by Django 5.0.9 on 2024-09-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_species',
        ),
    ]
