# Generated by Django 4.1.13 on 2024-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifications',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
