# Generated by Django 5.1.1 on 2024-09-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0002_rename_name_item_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
