# Generated by Django 5.0.9 on 2024-09-21 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0002_delete_all_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actinopterygii',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='actinopterygii',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='amphibia',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='amphibia',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='arachnida',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='arachnida',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='aves',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aves',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='insecta',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='insecta',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='mammalia',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mammalia',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='mollusca',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mollusca',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='plantae',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='plantae',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='protozoa',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='protozoa',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='reptilia',
            name='created_date',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reptilia',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='All_species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_date', models.DateField(verbose_name='Observed Date')),
                ('time_observed_at', models.TimeField(verbose_name='Time Observed At')),
                ('created_date', models.DateTimeField(verbose_name='Created At')),
                ('updated_date', models.DateTimeField(verbose_name='Updated At')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image URL')),
                ('description', models.TextField(max_length=10000, null=True, verbose_name='Description')),
                ('no_identification_agreement', models.BigIntegerField(default=0, verbose_name='Identification Agreements')),
                ('no_identification_disagreement', models.BigIntegerField(default=0, verbose_name='Identification Disagreements')),
                ('location', models.CharField(max_length=1000, null=True, verbose_name='Location')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('species_name_guess', models.CharField(max_length=1000, null=True, verbose_name='Species Guess')),
                ('scientific_name', models.CharField(max_length=1000, null=True, verbose_name='Scientific Name')),
                ('common_name', models.CharField(max_length=1000, verbose_name='Common Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=14, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=14, null=True, verbose_name='Longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
