# Generated by Django 4.1.13 on 2024-09-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0002_user_about_user_identifications_and_more'),
        ('wild_life', '0002_user_identifications_alter_user_last_login'),
    ]

    operations = [
    ]
