# Generated by Django 5.0.9 on 2024-09-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0003_alter_actinopterygii_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amphibia',
            name='updated_date',
        ),
    ]
