# Generated by Django 5.0.9 on 2024-09-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wild_life', '0004_remove_amphibia_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_species',
            name='user',
        ),
        migrations.RemoveField(
            model_name='amphibia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='arachnida',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aves',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insecta',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mammalia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mollusca',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plantae',
            name='user',
        ),
        migrations.RemoveField(
            model_name='protozoa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reptilia',
            name='user',
        ),
        migrations.DeleteModel(
            name='Actinopterygii',
        ),
        migrations.DeleteModel(
            name='All_species',
        ),
        migrations.DeleteModel(
            name='Amphibia',
        ),
        migrations.DeleteModel(
            name='Arachnida',
        ),
        migrations.DeleteModel(
            name='Aves',
        ),
        migrations.DeleteModel(
            name='Insecta',
        ),
        migrations.DeleteModel(
            name='Mammalia',
        ),
        migrations.DeleteModel(
            name='Mollusca',
        ),
        migrations.DeleteModel(
            name='Plantae',
        ),
        migrations.DeleteModel(
            name='Protozoa',
        ),
        migrations.DeleteModel(
            name='Reptilia',
        ),
    ]
